version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app
      - /usr/appnode_modules
    ports:
      - "8080:8080"
    environment:
      GCLOUD_PROJECT: cw-event-logger
      PUBSUB_TOPIC: cw-events