version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/src/
      - /usr/app/src/node_modules
    ports:
      - "8080:8080"
    environment:
      GCLOUD_PROJECT: cw-event-logger
      PUBSUB_TOPIC: cw-events